### ISSUE TITLE
[TicTacToe] Choose to be be the first or second player

### ISSUE THREAD

**Issue by mattiadg** [mattiadg/BoardGames#13]
This is another easy issue. Restructure the main.cpp of TicTacToe to let the user choose whether to play first or second.

**Comment by manishrw** [comment]
I'm taking this one.

**Comment by manishrw** [comment]
There is a bug building the code.

**Comment by mattiadg** [comment]
Can you please report the bug?

Il 11/Ott/2018 01:01 PM, "manish wadhwani" <notifications@github.com> ha
scritto:

**Comment by mattiadg** [comment]
ok, I see that you did a PR. What OS and compiler are you using?

Il 11/Ott/2018 01:35 PM, "mattia di gangi" <mattiadigangi@gmail.com> ha
scritto:

**Comment by mattiadg** [comment]
Sorry @manishrw, I was checking the comments from emails in my phone and I didn't notice that the PR was not from you. If you still want, feel free to add your as you picked the issue first.

**Comment by manishrw** [comment]
Done. #17
