### ISSUE TITLE
Remove hardcoded symbols

### ISSUE THREAD

**Issue by mattiadg** [mattiadg/BoardGames#19]
In the code there are symbols like '.' in the board representation or magic numbers that should be changed into variable names.
This is good for newcomers.

**Comment by MuchtarSalimov** [comment]
May I work on this?

I plan to follow the style seen [here](https://github.com/mattiadg/BoardGames/blob/master/TicTacToe/backend/TicTacToeBoardDescriptor.h) and just add them to the header files: 
`const int BOARD_SIZE = 9;`

**Comment by mattiadg** [comment]
Great, it's yours.

**Comment by mattiadg** [comment]
Addressed in #24 . Closing till the merging.
