### ISSUE TITLE
[TicTacToe] Informative outputs during game

### ISSUE THREAD

**Issue by mattiadg** [mattiadg/BoardGames#6]
This is very easy for newcomers and beginners. Just add information output during the game (whose turn it is, turn number, input format) and a prompt that asks the user to insert its input.

**Comment by Pansaai** [comment]
I would like to help with the issue @mattiadg

**Comment by mattiadg** [comment]
Please do it. You should modify the TicTacToe/main.cpp to add some prints
and help to understand what's going on.

Il 11/Ott/2018 12:22 PM, "Thomas Pans" <notifications@github.com> ha
scritto:

**Comment by mattiadg** [comment]
Issue solved #16
